### ISSUE TITLE
BUG Debian unstable

### ISSUE THREAD

**Issue by farhi** [mlerotic/spectromicroscopy#10]
Hello,

we have pushed a Debian package to easy installation on Debian, Ubuntu, Mint, etc.
- https://packages.debian.org/sid/mantis-xray
- https://tracker.debian.org/pkg/mantis-xray

However, with the current Debian dev branch (so called unstable which results in Ubuntu), an error message appears at start:
```
mantis-xray 
Loading file plugin: file_bim . Not a valid plugin - skipping.
Loading file plugin: file_csv . (text spectrum) Success!
Loading file plugin: file_dataexch_hdf5 . (Exchange) Success!
Loading file plugin: file_json . (JSON) Success!
Loading file plugin: file_ncb . (Ncb) Success!
Loading file plugin: file_nexus_hdf5 . (NXstxm) Success!
Loading file plugin: file_sdf . (SDF) Success!
Loading file plugin: file_sm_netcdf . Not a valid plugin - skipping.
Loading file plugin: file_stk . (STK) Success!
Loading file plugin: file_tif . (Tiff) Success!
Loading file plugin: file_xrm . (XRM) Success!
Traceback (most recent call last):
  File "/usr/bin/mantis-xray", line 33, in <module>
    sys.exit(load_entry_point('mantis-xray==3.0.11', 'gui_scripts', 'mantis-xray')())
  File "/usr/bin/mantis-xray", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/mantis_xray/mantis_qt.py", line 10528, in <module>
    class ShowHistogram(QtWidgets.QDialog, QtGui.QGraphicsScene):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QGraphicsScene'
```

Python version is 3.10
QT version is 5.15

Cheers, Emmanuel.

**Comment by Grumium** [comment]
QGraphicsScene inhertits from QtWidgets and not from QtGui in Qt5.
This bug was fixed long ago. The current version in the master branch of this repository is '3.1.8'.
I suggest updating the version in the corresponding package manager. The version on pypi '3.1.7' has it fixed and the new version is also mentioned here https://tracker.debian.org/pkg/mantis-xray

Cheers
JD

**Comment by farhi** [comment]
Then we just need to push the new mantis-xray 3.1.7 or later into salsa.debian.org to upgrade the package and fix the bug.
Thanks, Emmanuel.
