### ISSUE TITLE
AttributeError: Module 'scipy' has no attribute 'dot'

### ISSUE THREAD

**Issue by Leon-Schmidt** [mlerotic/spectromicroscopy#13]
Hello,
On MANTiS 3.1.15, installed via PyPI (both on Windows and Ubuntu), the tool fails to open with the following traceback:

```
Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.10/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
KeyError: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/leon/.local/lib/python3.10/site-packages/mantis_xray/__main__.py", line 30, in <module>
    sys.exit(main())
  File "/home/leon/.local/lib/python3.10/site-packages/mantis_xray/__main__.py", line 26, in main
    from . import mantis_qt
  File "/home/leon/.local/lib/python3.10/site-packages/mantis_xray/mantis_qt.py", line 63, in <module>
    from . import analyze
  File "/home/leon/.local/lib/python3.10/site-packages/mantis_xray/analyze.py", line 32, in <module>
    mmult = sp.dot
  File "/home/leon/.local/lib/python3.10/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'dot'
```

However, I could get MANTiS to open by changing line 32 in `analyze.py` from

`mmult = sp.dot`

to

`mmult = np.dot`

so to use numpy instead of scipy for the dot product, and it seems to work fine so far, but I'm not sure if the change breaks anything.

Thanks for your help !

**Comment by Grumium** [comment]
Yes, I came across this error recently.  
It has been fixed in [#792f48c860bcc289d7b61749c001d64ee1bf265d](https://github.com/mlerotic/spectromicroscopy/commit/792f48c860bcc289d7b61749c001d64ee1bf265d)

For the time being, replace the `analyze.py` with the one from the development branch or just continue using your fix. I cannot see any negative implications.
Another option would be to downgrade your scipy package to `scipy<=1.11.0`
