### ISSUE TITLE
Fails to open in Python 3.10

### ISSUE THREAD

**Issue by benajamin** [mlerotic/spectromicroscopy#7]
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\__main__.py", line 30, in <module>
    sys.exit(main())
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\__main__.py", line 27, in main
    mantis_qt.main()  # Open the GUI
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\mantis_qt.py", line 17087, in main
    frame = MainFrame()
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\mantis_qt.py", line 16312, in __init__
    self.initUI()
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\mantis_qt.py", line 16340, in initUI
    self.page1 = PageStack(self.common, self.data_struct, self.stk)
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\mantis_qt.py", line 8850, in __init__
    self.initUI(common, data_struct, stack)
  File "C:\Users\watts\AppData\Roaming\Python\Python310\site-packages\mantis_xray\mantis_qt.py", line 9092, in initUI
    self.slider_gamma.setValue(self.displaygamma)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

**Comment by benajamin** [comment]
fixed by commit ff8cfd96772f43eb2076d332e98c3b1e96f1dcbc
